const Lng = {
    Home:'الرئيسية',
    MAIN: 'Main',
    User: 'المستعمل',
    brand: 'LevelUp',
    register: 'إنشاء حساب',
    login: 'مرحبا بكم في عالمنا الحديث',
    user: 'المستعمل',
    item: 'العنصر',
    Information: 'معلومات',
    item_price: 'سعر السلعة:',
    Discount: 'خصم:',
    tax: 'ضريبة:',
    total: 'مجموع:',
    Payment_gateway: 'بوابة الدفع',
    pay: 'يدفع',
    have_giftcard: 'هل لديك خصم أو بطاقة هدية؟',
    profile: 'الملف الشخصي',
    support: 'الدعم',
    comments: 'تعليقات',
    lessons: 'الدروس',
    details: 'تفاصيل',
    leave_comment: 'اترك تعليقك ...',
    write_support: 'اترك رسالة الدعم الخاصة بك ...',
    support_is_disabled: 'الدورة غير مدعومة',
    send_support_massage: 'أرسل رسالة دعم',
    write_a_review: 'أكتب مراجعة',
    write_a_review_first: 'الرجاء كتابة مراجعة أولا',
    enroll_on_the_course: 'التسجيل في الدورة',
    newest_courses: 'أحدث الدورات',
    view_all: 'مشاهدة الكل',
    most_popular_courses: 'الدورات الأكثر شهرة',
    most_viewed_courses: 'الدورات الأكثر مشاهدة',
    featured_courses: 'الدورات المميزة',
    home: 'منزل، بيت ',
    onboarding1: 'ﺗﺼﻔﺢ اﻟﻌﺪﻳﺪ ﻣﻦ ﻛﻮرﺳﺎت اﻟﺘﻨﻤﻴﺔ اﻟﺒﴩﻳﺔ',
    onboarding1_sub: 'ﻫﺬا اﻟﻨﺺ ﻫﻮ ﻣﺜﺎل ﻟﻨﺺ يمکن أن ﻳﺴﺘﺒﺪل ﰲ ﻧﻔﺲ اﳌﺴﺎﺣﺔ، ﻟﻘﺪ ﺗﻢ ﺗﻮﻟﻴﺪ ﻫﺬا اﻟﻨﺺ ﻣﻦ ﻣﻮﻟﺪ اﻟﻨﺺ اﻟﻌﺮبى، ﺣﻴﺚ يمکنك أن ﺗﻮﻟﺪ ﻣﺜﻞ ﻫﺬا اﻟﻨﺺ',
    onboarding2: 'اﺷﱰك ﰲ اﻟﻜﻮرس اﻟﺬي ﺗﻔﻀﻞ',
    onboarding2_sub: 'ﻫﺬا اﻟﻨﺺ ﻫﻮ ﻣﺜﺎل ﻟﻨﺺ يمکن أن ﻳﺴﺘﺒﺪل ﰲ ﻧﻔﺲ اﳌﺴﺎﺣﺔ، ﻟﻘﺪ ﺗﻢ ﺗﻮﻟﻴﺪ ﻫﺬا اﻟﻨﺺ ﻣﻦ ﻣﻮﻟﺪ اﻟﻨﺺ اﻟﻌﺮبى، ﺣﻴﺚ يمکنك أن ﺗﻮﻟﺪ ﻣﺜﻞ ﻫﺬا اﻟﻨﺺ',
    onboarding3: 'ﺗﻮاﺻﻞ ﻣﻊ اﻣﻬﺮ اﳌﺪربين اﳌﻌﺘﻤﺪﻳﻦ',
    onboarding3_sub: 'ﻫﺬا اﻟﻨﺺ ﻫﻮ ﻣﺜﺎل ﻟﻨﺺ يمکن أن ﻳﺴﺘﺒﺪل ﰲ ﻧﻔﺲ اﳌﺴﺎﺣﺔ، ﻟﻘﺪ ﺗﻢ ﺗﻮﻟﻴﺪ ﻫﺬا اﻟﻨﺺ ﻣﻦ ﻣﻮﻟﺪ اﻟﻨﺺ اﻟﻌﺮبى، ﺣﻴﺚ يمکنك أن ﺗﻮﻟﺪ ﻣﺜﻞ ﻫﺬا اﻟﻨﺺ',
    onboarding4: 'اﺷﱰك ﰲ اﻟﻜﻮرس اﻟﺬي ﺗﻔﻀﻞ',
    onboarding4_sub: 'ﻫﺬا اﻟﻨﺺ ﻫﻮ ﻣﺜﺎل ﻟﻨﺺ يمکن أن ﻳﺴﺘﺒﺪل ﰲ ﻧﻔﺲ اﳌﺴﺎﺣﺔ، ﻟﻘﺪ ﺗﻢ ﺗﻮﻟﻴﺪ ﻫﺬا اﻟﻨﺺ ﻣﻦ ﻣﻮﻟﺪ اﻟﻨﺺ اﻟﻌﺮبى، ﺣﻴﺚ يمکنك أن ﺗﻮﻟﺪ ﻣﺜﻞ ﻫﺬا اﻟﻨﺺ',
    search: 'يبحث...',
    Category: 'التصنيفات',
    course_categories: 'فئات الدورة',
    News: 'الإخبارية',
    More: 'أكثر',
    Latest_news: 'أحدث الأخبار',
    Latest_articles: 'أحدث المقالات',
    coming_soon_courses: 'قريبا الدورات',
    Course_requests: 'طلبات الدورة',
    Follow: 'يتبع',
    Courses: 'الدورات',
    my_courses: 'دوراتي',
    back_to_categories: 'رجوع إلى الفئات',
    Minutes: 'الدقائق',
    Followers: 'متابعون',
    Bio: 'حول',
    Badges: 'شارات',
    Articles: 'مقالات',
    Login: 'تسجيل الدخول',
    Send: 'إرسال',
    please_login: 'يرجى تسجيل الدخول إلى حسابك.',
    purchase_first: 'عنصر لم يتم شراؤه!',
    Email_address: 'بريدك الالكتروني',
    Password: 'كلمة المر',
    re_password: 'أعد إدخال كلمة السر:',
    access_denied: 'تم الرفض! حسابك محظور حتى:',
    incorrect_login: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    pass_confirm_alert: 'كلمة المرور وتأكيد كلمة المرور غير متطابقين.',
    password_changed: 'تم تغيير الرقم السري بنجاح.',
    user_not_found: 'لم يتم العثور على المستخدم!',
    pass_change_link: 'تم إرسال رابط تغيير كلمة المرور إلى بريدك الإلكتروني.',
    new_pass_email: 'تم إرسال كلمة المرور الجديدة إلى بريدك الإلكتروني.',
    user_exists: 'المستخدم موجود بالفعل مع المعلومات المدخلة',
    thanks_reg: 'شكرا للتسجيل!',
    active_account_alert: 'شكرًا للتسجيل ، يرجى التحقق من بريدك واتباع رابط التفعيل لتفعيل حسابك',
    login_request: 'الرجاء تسجيل الدخول إلى حسابك لإرسال الطلب.',
    Register: 'إنشاء حساب',
    email_ph: 'بريدك الالكتروني',
    username_ph: 'اسم المستخدم الخاص بك',
    retype_ph: 'أعد إدخال كلمة السر',
    realname_ph: 'اسمك الحقيقي',
    password_ph: 'كلمة مرورك',
    enjoy_product: 'واستمتع بـLevelUp! ',
    forget_password: 'نسيت كلمة المرور',
    Already_have_an_account: 'هل لديك حساب؟',
    Your_problem_solved: 'حل مشكلتك؟',
    Back_to_Login: 'العودة إلى تسجيل الدخول',
    simply_email: 'ببساطة عن طريق البريد الإلكتروني',
    recover: 'استعادة كلمة المرور الخاصة بك',
    reset_password: 'إعادة تعيين كلمة المرور',
    enter_email_reset_password: 'أدخل عنوان بريدك الإلكتروني ، سيتم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.',
    username: 'اسم المستخدم:',
    login_to_purchase: 'الرجاء تسجيل الدخول لشراء الدورة.',
    i_accept: 'أنا موافق',
    term_rules: 'الشروط والقواعد',
    entered_username_exists: 'اسم المستخدم الذي تم إدخاله موجود ، جرب اسم مستخدم آخر.',
    entered_email_exists: 'البريد الإلكتروني المدخل موجود ، حاول مرة أخرى.',
    pass_confirmation_same: 'كلمات المرور هذه غير متطابقة ، حاول مرة أخرى.',
    activation: 'تفعيل',
    successfully_done: 'فعلت بنجاح!',
    account_activation_success: 'تم تفعيل حسابك بنجاح.',
    Dashboard: 'لوحة القيادة',
    Channels: 'القنوات',
    Channel: 'قناة',
    Financial: 'الأمور المالية',
    My_courses: 'دوراتي',
    My_purchases: 'مشترياتي',
    Free: 'حر',
    Published: 'نشرت',
    draft: 'مسودة',
    waiting: 'منتظر',
    unpublish_request: 'طلب إلغاء النشر',
    Sales: 'المبيعات',
    new_sales: 'مبيعات جديدة',
    new_postal_sales: 'مبيعات البريد الجديدة',
    New_message: 'رسالة جديدة',
    new_comment: 'تعليقات جديدة',
    account_summary: 'ملخص الحساب',
    Account_charge: 'رسوم الحسابe',
    today_sales: 'مبيعات اليوم:',
    monthly_sales: 'المبيعات الشهرية:',
    total_sale: 'إجمالي المبيعات:',
    total_income: 'إجمالي الدخل:',
    Start_learning: 'من فضلك قم بتسجيل الدخول أ',
    Ready_to_payout: 'جاهز للدفع:',
    start_teaching: 'ابدأ التدريس اليوم',
    become_insructor: 'كن مدربًا',
    total_purchase: 'إجمالي المشتريات:',
    current_sales_badge: 'شارة المبيعات الحالية:',
    your_total_sales: 'إجمالي المبيعات:',
    Balance: 'أرصدة',
    charge_account: 'حساب الشحن',
    new_ticket: 'تذكرة جديدة',
    write_message: 'اكتب رسالتك...',
    Attach: 'أرفق ملف',
    close: 'يغلق',
    reply_message: 'رسالة الرد',
    new_messages: 'رسائل جديدة',
    Charge: 'الشحنة',
    purchased_items: 'البنود التي تم شراؤها',
    sold_item: 'البند المباع',
    Automatic: 'تلقائي',
    manual: 'كتيب',
    Payoutable: 'الدفع',
    replied: 'أجاب',
    Reply: 'رد',
    Staff: 'العاملين',
    empty_field: 'لا يمكن أن يكون الحقل فارغًا!',
    Comments: 'تعليقات',
    Settings: 'إعدادات',
    change_pass: 'تغيير كلمة المرور',
    Students: 'الطلاب',
    Instructor: 'مدرب',
    not_defined: 'غير معرف.',
    //Settings
    customText : 'سجل في واحصل على العديد\n من الدورات التدريبية الرائعة',
    account_info: 'معلومات الحساب',
    realname: 'الاسم الحقيقي:',
    email: 'بريد إلكتروني',
    biography: 'سيرة شخصية',
    short_biography: 'سيرة ذاتية قصيرة',
    province: 'المحافظة',
    city: 'مدينة',
    birthday: 'عيد ميلاد',
    age: 'سن',
    name: 'اسم',
    Save: 'يحفظ',
    phone_number: 'رقم الهاتف',
    personal_info: 'معلومات شخصيةo',
    bank_name: 'اسم البنك',
    account_number: 'رقم حساب',
    creditcard: 'بطاقة إئتمان',
    identity_scan: 'فحص الهوية',
    passport_id: 'رقم جواز السفر.',
    images: 'الصور',
    avatar: 'الصورة الرمزية',
    profile_cover: 'غلاف الملف الشخصي',
    new_password: 'كلمة السر الجديدة',
    retype_password: 'أعد إدخال كلمة السر',
    security: 'حماية',
    postal: 'بريدي',
    zip_code: 'الرمز البريدي',
    address: 'عنوان',
    financial_approved: 'تمت الموافقة على المعلومات المالية الخاصة بك. لتغيير هذه المعلومات اتصل بالدعم.',
    //Channel
    follow: 'يتبع',
    unfollow: 'الغاء المتابعة',
    check:'الشيك',
    incorrect_code:'شفرة خاطئة',
    purchase_failed: 'الشراء لم ينجح!',
    no_credit:'الائتمان لا يكفي!',
    download:'تحميل',
    become_vendor:'افتح متجرك في سوق البلد',
    send_successfully:'أرسل بنجاح!',
    live:'حي',
    Quizzes:'الإختبارات',
    Certificates:'الشهادات',
    Filter:'منقي',
    Paid:'مدفوع',
    All:'الجميع',
    Price:'سعر',
    Single:'أعزب',
    welcome : 'مرحبا بك من جد يد',
    welcomeSub : "ماذا تود ان تتعلم اليوم",
    Webinar:'نقاش عبر الويب',
    Course:'مسار',
    Physical:'جسدي - بدني',
    Support:'الدعم',
    filter_discount:'خصم',
    customMenuText : 'أنواع الدورات',
    PrivacyText : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    Privacy : "سياسة خاصة",
    terms : "الأحكام والشروط",
}
const Lng2 = {
    Home:'Home',
    MAIN: 'Main',
    User: 'User',
    brand: 'LevelUp',
    register: 'Register',
    login: 'Login',
    user: 'User',
    item: 'Item',
    Information: 'Information',
    item_price: 'Item price:',
    Discount: 'Discount:',
    tax: 'Tax:',
    total: 'Total:',
    Payment_gateway: 'Payment gateway',
    pay: 'Pay',
    have_giftcard: 'Have discount or gift card?',
    profile: 'Profile',
    support: 'Support',
    comments: 'Comments',
    lessons: 'Lessons',
    details: 'Details',
    leave_comment: 'Leave your comment...',
    write_support: 'Leave your support message...',
    support_is_disabled: 'Course not supported',
    send_support_massage: 'Send support massage',
    write_a_review: 'Write a review',
    write_a_review_first: 'Please write a review first',
    enroll_on_the_course: 'Enroll on the course',
    newest_courses: 'Newest courses',
    view_all: 'View All',
    most_popular_courses: 'Most popular courses',
    most_viewed_courses: 'Most viewed courses',
    featured_courses: 'Featured courses',
    home: 'Home',
    onboarding1: 'Learn everywhere',
    onboarding1_sub: 'with LevelUp',
    onboarding2: 'Teach your skills easily',
    onboarding2_sub: 'and earn money',
    onboarding3: 'Become skillful',
    onboarding3_sub: 'and invest on yourself',
    search: 'Search...',
    Category: 'Category',
    course_categories: 'Course categories',
    News: 'News',
    More: 'More',
    Latest_news: 'Latest news',
    Latest_articles: 'Latest articles',
    coming_soon_courses: 'Coming soon courses',
    Course_requests: 'Course requests',
    Follow: 'Follow',
    Courses: 'Courses',
    my_courses: 'My courses',
    back_to_categories: 'Back to categories',
    Minutes: 'Minutes',
    Followers: 'Followers',
    Bio: 'About',
    Badges: 'Badges',
    Articles: 'Articles',
    Login: 'Login',
    Send: 'Send',
    please_login: 'Please login to your account.',
    purchase_first: 'Item not purchased!',
    Email_address: 'Email address:',
    Password: 'Password:',
    re_password: 'Retype Password:',
    access_denied: 'Access denied! Your account banned until: ',
    incorrect_login: 'Incorrect username or password',
    pass_confirm_alert: 'Password and confirm password does not match.',
    password_changed: 'Password changed successfully.',
    user_not_found: 'User not found!',
    pass_change_link: 'Password change link sent to your email.',
    new_pass_email: 'New password sent to your email.',
    user_exists: 'User already exists with entered information',
    thanks_reg: 'Thanks for registration!',
    active_account_alert: 'Thanks for registration, Please check your mail and follow activation link to active your account.',
    login_request: 'Please login to your account to send request.',
    Register: 'Register',
    email_ph: 'Your email',
    username_ph: 'Your username',
    retype_ph: 'Retype password',
    realname_ph: 'Your real name',
    password_ph: 'Your password',
    enjoy_product: 'and enjoy LevelUp!',
    forget_password: 'Forgot your password?',
    Already_have_an_account: 'Already have an account?',
    Your_problem_solved: 'Your problem solved?',
    Back_to_Login: 'Back to Login',
    simply_email: 'simply by email',
    recover: 'Recover your password',
    reset_password: 'Reset Password',
    enter_email_reset_password: 'Enter your email address, Password reset link will be sent to your email.',
    username: 'Username:',
    login_to_purchase: 'Please login to purchase the course.',
    i_accept: 'I agree',
    term_rules: 'Terms & Rules',
    entered_username_exists: 'Entered username exists, Try another.',
    entered_email_exists: 'Entered email exists, Try another.',
    pass_confirmation_same: 'Those passwords didnt match, Try again.',
    active_account: 'Account activation',
    activation: 'Activation',
    successfully_done: 'Successfully done!',
    account_activation_success: 'Your account activated successfully.',
    Dashboard: 'Dashboard',
    Channels: 'Channels',
    Channel: 'Channel',
    Financial: 'Financial',
    My_courses: 'My courses',
    My_purchases: 'My purchases',
    Free: 'Free',
    Published: 'Published',
    draft: 'Draft',
    waiting: 'Waiting',
    unpublish_request: 'Unpublish Request',
    Sales: 'Sales',
    new_sales: 'New Sales',
    new_postal_sales: 'New Postal Sales',
    New_message: 'New Message',
    new_comment: 'New Comments',
    account_summary: 'Account summary',
    Account_charge: 'Account charge',
    today_sales: 'Today Sales:',
    monthly_sales: 'Monthly Sales:',
    total_sale: 'Total Sales:',
    total_income: 'Total Income:',
    Start_learning: 'Start learning and teaching',
    Ready_to_payout: 'Ready to payout:',
    start_teaching: 'Start teaching today',
    become_insructor: 'Become an instructor',
    total_purchase: 'Total Purchases:',
    current_sales_badge: 'Current Sales Badge:',
    your_total_sales: 'Total Sales:',
    Balance: 'Balances',
    charge_account: 'Charge account',
    new_ticket: 'New ticket',
    write_message: 'Write your message...',
    Attach: 'Attach file',
    close: 'Close',
    reply_message: 'Reply message',
    new_messages: 'New messages',
    Charge: 'Charge',
    purchased_items: 'Purchased items',
    sold_item: 'Sold item',
    Automatic: 'Automatic',
    manual: 'manual',
    Payoutable: 'Payoutable',
    replied: 'Replied',
    Reply: 'Reply',
    Staff: 'Staff',
    empty_field: 'The field couldnt be empty!',
    Comments: 'Comments',
    Settings: 'Settings',
    change_pass: 'Change password',
    Students: 'Students',
    Instructor: 'Instructor',
    not_defined: 'Not Defined.',
    //Settings
    account_info: 'Account info',
    realname: 'Real Name:',
    email: 'Email',
    biography: 'Biography',
    short_biography: 'Short Biography',
    province: 'Province',
    city: 'City',
    birthday: 'Birthday',
    age: 'Age',
    name: 'Name',
    Save: 'Save',
    phone_number: 'Phone Number',
    personal_info: 'Personal info',
    bank_name: 'Bank Name',
    account_number: 'Account Number',
    creditcard: 'Credit Card',
    identity_scan: 'Identity Scan',
    passport_id: 'Passport Id.',
    images: 'Images',
    avatar: 'Avatar',
    profile_cover: 'Profile Cover',
    new_password: 'New Password',
    retype_password: 'Retype Password',
    security: 'Security',
    postal: 'Postal',
    zip_code: 'Zip code',
    address: 'Address',
    financial_approved: 'Your financial information approved. To change this information contact support.',
    //Channel
    follow: 'Follow',
    unfollow: 'Unfollow',
    check:'Check',
    incorrect_code:'Incorrect code',
    purchase_failed: 'Purchase failed!',
    no_credit:'Credit is not enough!',
    download:'Download',
    become_vendor:'Become a vendor',
    send_successfully:'Send Successfully!',
    live:'Live',
    Quizzes:'Quizzes',
    Certificates:'Certificates',
    Filter:'Filter',
    Paid:'Paid',
    All:'All',
    Price:'Price',
    Single:'Single',
    Webinar:'Webinar',
    welcome : "Welcome Again,",
    welcomeSub : 'What will you like to Learn Today?',
    Course:'Course',
    Physical:'Physical',
    Support:'Support',
    filter_discount:'Discount',
    customMenuText : 'Types of Courses',
    customText : 'Register for LevelUp and Get Many Amazing Courses',
    Privacy : "Privacy Policy",
    terms : "Terms and Conditions",
    PrivacyText : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
}

export {Lng}
export {Lng2}
